# Generated by Django 5.0.1 on 2024-05-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_userprofile_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('Months_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('course', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='accounts.course')),
            ],
        ),
    ]
