# Generated by Django 5.0.1 on 2024-05-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_course_student_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lectureHrs',
            new_name='Duration',
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='course', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='student', to='accounts.course'),
        ),
    ]
