# Generated by Django 5.0.1 on 2024-05-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
