# Generated by Django 5.0.1 on 2024-05-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_present_days_attendance_total_days_present_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='total_days_present',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.CharField(max_length=7),
        ),
        migrations.CreateModel(
            name='TotalAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_days_present', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
