# Generated by Django 5.0.1 on 2024-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_today_today_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_fee',
            field=models.IntegerField(default=0),
        ),
    ]
